import 'package:booking_management/models/book.dart';

List<Book> booklists =[ 

    Book(
      title: 'One day',
      author: 'David Nicholls',
      genre: 'Romance',
      publicationDate: DateTime(2009, 6, 11), 
      coverImage: 'assets/oneday.png', // Path to the cover image
      isBorrowed: false,
      isReserved: false,
    ),
    Book(
      title: 'When breath becomes air',
      author: 'Paul Kalanithi',
      genre: 'Nonfiction',
      publicationDate: DateTime(2016, 1, 12),
      coverImage: 'assets/breathair.png',
      isBorrowed: true,
      isReserved: false,
    ),
    Book(
      title: 'Kill Joy A Good Girl’s Guide to Murder 5',
      author: 'Holly Jackson',
      genre: 'Crime',
      publicationDate: DateTime(2021, 2, 18),
      coverImage: 'assets/ggm5.png',
      isBorrowed: false,
      isReserved: true,
    ),
    Book(
      title: 'A Good Girl’s Guide to Murder 1',
      author: 'Holly Jackson',
      genre: 'Crime',
      publicationDate: DateTime(2019, 5, 2),
      coverImage: 'assets/ggm1.png',
      isBorrowed: false,
      isReserved: false,
    ),
    Book(
      title: 'A Good Girl’s Guide to Murder 2',
      author: 'Holly Jackson',
      genre: 'Crime',
      publicationDate: DateTime(2020, 4, 30),
      coverImage: 'assets/ggm2.png',
      isBorrowed: false,
      isReserved: false,
    ),
    Book(
      title: 'As Good As Dead (A Good Girl’s Guide to Murder 3)',
      author: 'Holly Jackson',
      genre: 'Crime',
      publicationDate: DateTime(2021, 8, 5),
      coverImage: 'assets/ggm3.png',
      isBorrowed: true,
      isReserved: false,
    ),
    Book(
      title: 'War and Peace',
      author: 'Leo Tolstoy',
      genre: 'Historical Fiction',
      publicationDate: DateTime(1869, 1, 1),
      coverImage: 'assets/ggm3.png',
      isBorrowed: false,
      isReserved: false,
    ),
    Book(
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      genre: 'Fantasy',
      publicationDate: DateTime(1937, 9, 21),
      coverImage: 'assets/ggm3.png',
      isBorrowed: false,
      isReserved: true,
    ),
    Book(
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      genre: 'Adventure',
      publicationDate: DateTime(1988, 5, 1),
      coverImage: 'assets/ggm3.png',
      isBorrowed: false,
      isReserved: false,
    ),
    Book(
      title: 'The Picture of Dorian Gray',
      author: 'Oscar Wilde',
      genre: 'Philosophical Fiction',
      publicationDate: DateTime(1890, 6, 20),
      coverImage: 'assets/ggm3.png',
      isBorrowed: false,
      isReserved: false,
    ),
  ];

